vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: '%app.path.user_image%'
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        trade_image:
            uri_prefix: /images/trades
            upload_destination: '%kernel.project_dir%/public/images/trades'
        document:
            uri_prefix: /documents
            upload_destination: '%kernel.project_dir%/public/documents'