easy_admin:
  entities:

    County:
      class: App\Entity\County
      list:
        fields: ['id',{ property: 'name', label: 'Nom' }, {property: 'users', label: 'Royaumiens'}]
      label: 'Cellules'
      form:
        fields:
          - { property: 'name', label: 'Nom'}