easy_admin:
  entities:

    Document:
      class: App\Entity\Document
      list:
        actions: ['show']
        fields: ['id',
                 { property: 'fileName', label: 'Nom' },
                 { property: 'fileName', label: 'Fichier', type: 'image', base_path: '/documents'},
                 { property: 'fileSize', label: 'Taille (ko)' },
                 { property: 'fileMimeType', label: 'Type' },
                 { property: 'fileCategory', label: 'Dossier' }]
      show:
        fields: ['id',
                 { property: 'fileName', label: 'Nom' },
                 { property: 'fileName', label: 'Fichier', type: 'image', base_path: '/documents' },
                 { property: 'fileSize', label: 'Taille (ko)' },
                 { property: 'fileMimeType', label: 'Type' },
                 { property: 'fileCategory', label: 'Dossier' }]
      label: 'Documents'
      form:
        fields:
          - { property: 'file', label: 'Document', type: 'vich_file' }
          - { property: 'fileCategory', label: 'Dossier', type: 'entity', type_options: {class: App\Entity\FileCategory} }