easy_admin:
  entities:

    Document:
      class: App\Entity\Document
      list:
        fields: ['id', { property: 'fileName', label: 'Fichier' } ,{ property: 'fileSize', label: 'Taille' } ,{ property: 'fileMimeType', label: 'Type' }]
      label: 'Documents'
      form:
        fields:
          - { property: 'file', label: 'Document', type: 'vich_file' }