easy_admin:
  entities:

    Trade:
      class: App\Entity\Trade
      list:
        fields: ['id',
                 { property: 'name', label: 'Nom' },
                 { property: 'imageName', label: 'Logo' },]
      label: 'Corps de métier'
      form:
        fields:
          - { property: 'name', label: 'Nom'}
          - { property: 'imageFile', label: 'Logo', type: 'vich_image' }