easy_admin:
  entities:

    Trade:
      class: App\Entity\Trade
      list:
        fields: ['id',
                 { property: 'name', label: 'Nom' },
                 { property: 'users', label: 'Royaumiens' },
                 { property: 'imageName', label: 'Logo' },
                 { property: 'imageName', label: 'Logo', type: 'image', base_path: '/images/trades' },]
      label: 'Corps de métier'
      form:
        fields:
          - { property: 'name', label: 'Nom'}
          - { property: 'imageFile', label: 'Logo', type: 'vich_image' }