easy_admin:
  entities:

    User:
      class: App\Entity\User
      list:
        actions: ['show']
        disabled_actions: ['new']

        fields: ['id',
                 { property: 'fullname', label: 'Nom' },
                 { property: 'email', label: 'Email' },
                 { property: 'buddy', label: 'Parrain'},
                 { property: 'godChildren', label: 'Filleul'},
                 { property: 'enteredAt', label: "Année d'entrée" },
                 { property: 'knightedAt', label: "Année d'adoubement" },
                 { property: 'county', label: 'Celulle' },
                 { property: 'phone', label: 'Téléphone' }]
      label: 'Royaumiens'
      edit:
        fields:
          - { property: 'firstname', label: 'Prénom'}
          - { property: 'lastname', label: 'Nom'}
          - { property: 'enteredAt', label: "Année d'entrée au royaume", type_options: { widget: 'single_text' } }
          - { property: 'buddy', label: 'Parrain',type: 'entity', type_options: {class: App\Entity\User}}
          - { property: 'godChildren', label: 'Filleul',type: 'easyadmin_autocomplete', type_options: {class: App\Entity\User, multiple: true}}
          - { property: 'knightedAt', label: "Année d'adoubement", type_options: { widget: 'single_text' }}
          - { property: 'county', label: 'Cellule',type: 'entity', type_options: {class: App\Entity\County}}
          - { property: 'phone', label: 'Téléphone', type: 'tel' }
          - { property: 'email', label: 'Email', type: 'email' }
          - { property: 'jobs', label: 'Métiers',type: 'entity', type_options: {class: App\Entity\Job}}
          - { property: 'imageFile', label: 'Photo de profil', type: 'vich_image' }
      show:
        fields:
          - { property: 'firstname', label: 'Prénom'}
          - { property: 'lastname', label: 'Nom'}
          - { property: 'enteredAt', label: "Année d'entrée au royaume"}
          - { property: 'buddy', label: 'Parrain'}
          - { property: 'godChildren', label: 'Filleul'}
          - { property: 'knightedAt', label: "Année d'adoubement"}
          - { property: 'county', label: 'Cellule'}
          - { property: 'phone', label: 'Téléphone', type: 'tel' }
          - { property: 'email', label: 'Email', type: 'email' }
          - { property: 'jobs', label: 'Métiers'}